/** @type { ActionRun } */
export const run = async ({ params, logger, api, connections }) => {
  const orderCount = params.orderCount || 20;
  
  // Load the shop
  const shop = await api.shopifyShop.findOne(params.shopId, {
    select: { id: true, domain: true }
  });
  
  logger.info({ shopId: params.shopId, sku: params.sku, orderCount }, "Starting test order generation");
  
  // Get Shopify API client
  const shopify = await connections.shopify.forShopId(params.shopId);
  
  // Find the product by SKU using GraphQL
  const productQuery = `
    query {
      productVariants(first: 1, query: "sku:${params.sku}") {
        edges {
          node {
            id
            sku
            price
            product {
              id
              title
            }
          }
        }
      }
    }
  `;
  
  const productData = await shopify.graphql(productQuery);
  const variant = productData.productVariants.edges[0]?.node;
  
  if (!variant) {
    throw new Error(`Product with SKU ${params.sku} not found`);
  }
  
  // Extract numeric variant ID from GraphQL ID (e.g., "gid://shopify/ProductVariant/123" -> "123")
  const variantIdMatch = variant.id.match(/\/(\d+)$/);
  if (!variantIdMatch) {
    throw new Error(`Could not extract numeric ID from variant ID: ${variant.id}`);
  }
  const numericVariantId = variantIdMatch[1];
  
  logger.info({ variantId: variant.id, numericVariantId, productTitle: variant.product.title }, "Found product variant");
  
  // Generate orders with varied data
  const createdOrders = [];
  
  for (let i = 0; i < orderCount; i++) {
    try {
      // Vary quantities: 1-5 items per order
      const quantity = Math.floor(Math.random() * 5) + 1;
      
      // Vary dates: spread across last 7 days (for note reference)
      const daysAgo = Math.floor(Math.random() * 7);
      const orderDate = new Date();
      orderDate.setDate(orderDate.getDate() - daysAgo);
      
      // Create order via REST API
      const order = await shopify.order.create({
        line_items: [
          {
            variant_id: parseInt(numericVariantId),
            quantity: quantity
          }
        ],
        email: `customer${i}@test.com`,
        financial_status: 'paid',
        send_receipt: false,
        send_fulfillment_receipt: false,
        tags: 'test, gadget-generated',
        note: `Test order ${i + 1} generated by Gadget (simulated date: ${orderDate.toISOString()})`
      });
      
      createdOrders.push({ 
        orderId: order.id, 
        orderName: order.name, 
        quantity 
      });
      
      logger.info({ orderName: order.name, quantity }, `Created test order ${i + 1}/${orderCount}`);
    } catch (error) {
      logger.error({ error: error.message, orderIndex: i }, `Error creating order ${i + 1}`);
      continue;
    }
  }
  
  // Return summary
  return {
    success: true,
    shopId: params.shopId,
    sku: params.sku,
    ordersCreated: createdOrders.length,
    totalRequested: orderCount,
    orders: createdOrders
  };
};

export const params = {
  shopId: { type: "string" },
  sku: { type: "string" },
  orderCount: { type: "number" }
};
