import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://stockeasy-app.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Shop",
  fields: {
    billingActivatedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "billing-activated-at",
    },
    defaultLocationId: {
      type: "string",
      storageKey: "Drj386y1GY1H",
      filterIndex: false,
      searchIndex: false,
    },
    shopifySubscriptionId: {
      type: "string",
      storageKey: "billing-shopify-subscription-id",
    },
    stockEasyCompanyId: {
      type: "string",
      storageKey: "l8xRsYW24z-0",
    },
    subscriptionPlan: {
      type: "string",
      default: "basic",
      storageKey: "billing-subscription-plan",
    },
    subscriptionStatus: {
      type: "enum",
      default: "pending",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["active", "cancelled", "frozen", "pending", "trial"],
      storageKey: "billing-subscription-status",
    },
    trialEndsAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "billing-trial-ends-at",
    },
    trialStartedAt: {
      type: "dateTime",
      includeTime: true,
      storageKey: "billing-trial-started-at",
    },
  },
  shopify: {
    fields: {
      address1: { filterIndex: false },
      address2: { filterIndex: false },
      alerts: { filterIndex: false, searchIndex: false },
      appInstallations: true,
      billingAddress: { filterIndex: false },
      checkoutApiSupported: {
        filterIndex: false,
        searchIndex: false,
      },
      city: { filterIndex: false },
      countriesInShippingZones: {
        filterIndex: false,
        searchIndex: false,
      },
      country: { filterIndex: false },
      countryCode: { filterIndex: false },
      countryName: { filterIndex: false },
      countyTaxes: { filterIndex: false, searchIndex: false },
      currency: { filterIndex: false, searchIndex: false },
      currencyFormats: { filterIndex: false, searchIndex: false },
      customerAccounts: { filterIndex: false, searchIndex: false },
      customerAccountsV2: { filterIndex: false, searchIndex: false },
      customerEmail: { filterIndex: false },
      description: { filterIndex: false },
      domain: true,
      eligibleForPayments: { filterIndex: false, searchIndex: false },
      email: true,
      enabledPresentmentCurrencies: {
        filterIndex: false,
        searchIndex: false,
      },
      finances: { filterIndex: false, searchIndex: false },
      gdprRequests: true,
      googleAppsDomain: { filterIndex: false, searchIndex: false },
      googleAppsLoginEnabled: {
        filterIndex: false,
        searchIndex: false,
      },
      hasDiscounts: { filterIndex: false, searchIndex: false },
      hasGiftCards: { filterIndex: false, searchIndex: false },
      hasStorefront: { filterIndex: false, searchIndex: false },
      ianaTimezone: { filterIndex: false, searchIndex: false },
      inventoryItems: true,
      inventoryLevels: true,
      latitude: { filterIndex: false, searchIndex: false },
      locations: true,
      longitude: { filterIndex: false, searchIndex: false },
      marketingSmsContentEnabledAtCheckout: {
        filterIndex: false,
        searchIndex: false,
      },
      moneyFormat: { filterIndex: false, searchIndex: false },
      moneyInEmailsFormat: { filterIndex: false, searchIndex: false },
      moneyWithCurrencyFormat: {
        filterIndex: false,
        searchIndex: false,
      },
      moneyWithCurrencyInEmailsFormat: {
        filterIndex: false,
        searchIndex: false,
      },
      multiLocationEnabled: {
        filterIndex: false,
        searchIndex: false,
      },
      myshopifyDomain: true,
      name: true,
      orderLineItems: true,
      orderNumberFormatPrefix: {
        filterIndex: false,
        searchIndex: false,
      },
      orderNumberFormatSuffix: {
        filterIndex: false,
        searchIndex: false,
      },
      orders: true,
      passwordEnabled: { filterIndex: false, searchIndex: false },
      phone: { filterIndex: false },
      plan: true,
      planDisplayName: true,
      planName: true,
      planPublicDisplayName: true,
      preLaunchEnabled: { filterIndex: false, searchIndex: false },
      primaryLocale: { filterIndex: false, searchIndex: false },
      primaryLocation: { searchIndex: false },
      products: true,
      province: { filterIndex: false },
      provinceCode: { filterIndex: false },
      requiresExtraPaymentsAgreement: {
        filterIndex: false,
        searchIndex: false,
      },
      resourceLimits: { filterIndex: false, searchIndex: false },
      richTextEditorUrl: { filterIndex: false, searchIndex: false },
      setupRequired: { filterIndex: false, searchIndex: false },
      shipsToCountries: { filterIndex: false, searchIndex: false },
      shopOwner: { filterIndex: false },
      shopifyCreatedAt: { filterIndex: false, searchIndex: false },
      shopifyUpdatedAt: { filterIndex: false, searchIndex: false },
      source: { filterIndex: false, searchIndex: false },
      syncs: true,
      taxShipping: { filterIndex: false, searchIndex: false },
      taxesIncluded: { filterIndex: false, searchIndex: false },
      timezone: { filterIndex: false, searchIndex: false },
      timezoneAbbreviation: {
        filterIndex: false,
        searchIndex: false,
      },
      timezoneOffset: { filterIndex: false, searchIndex: false },
      timezoneOffsetMinutes: {
        filterIndex: false,
        searchIndex: false,
      },
      transactionalSmsDisabled: {
        filterIndex: false,
        searchIndex: false,
      },
      unitSystem: { filterIndex: false, searchIndex: false },
      url: { filterIndex: false },
      weightUnit: { filterIndex: false, searchIndex: false },
      zipCode: { filterIndex: false, searchIndex: false },
    },
  },
};
