import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyOrder" model, go to https://stockeasy-app.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v2",
  storageKey: "DataModel-Shopify-Order",
  fields: {},
  shopify: {
    fields: {
      additionalFees: { filterIndex: false, searchIndex: false },
      alerts: { filterIndex: false, searchIndex: false },
      billingAddress: { filterIndex: false },
      billingStatusMatchesShippingAddress: {
        filterIndex: false,
        searchIndex: false,
      },
      browserIp: { filterIndex: false, searchIndex: false },
      buyerAcceptsMarketing: {
        filterIndex: false,
        searchIndex: false,
      },
      canMarkAsPaid: { filterIndex: false, searchIndex: false },
      canNotifyCustomer: { filterIndex: false, searchIndex: false },
      cancelReason: { filterIndex: false, searchIndex: false },
      cancellation: { filterIndex: false, searchIndex: false },
      cancelledAt: { searchIndex: false },
      capturable: { filterIndex: false, searchIndex: false },
      cartDiscountAmountSet: {
        filterIndex: false,
        searchIndex: false,
      },
      cartToken: { filterIndex: false, searchIndex: false },
      checkoutToken: { searchIndex: false },
      clientDetails: { filterIndex: false },
      closed: { filterIndex: false, searchIndex: false },
      closedAt: { filterIndex: false, searchIndex: false },
      confirmationNumber: { filterIndex: false, searchIndex: false },
      confirmed: { filterIndex: false, searchIndex: false },
      currency: { filterIndex: false, searchIndex: false },
      currentCartDiscountAmountSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentShippingPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentSubtotalLineItemsQuantity: {
        filterIndex: false,
        searchIndex: false,
      },
      currentSubtotalPrice: {
        filterIndex: false,
        searchIndex: false,
      },
      currentSubtotalPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalAdditionalFeesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDiscounts: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDiscountsSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalDutiesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalPrice: { filterIndex: false, searchIndex: false },
      currentTotalPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      currentTotalTax: { filterIndex: false, searchIndex: false },
      currentTotalTaxSet: { filterIndex: false, searchIndex: false },
      currentTotalWeight: { filterIndex: false, searchIndex: false },
      customerJourneySummary: {
        filterIndex: false,
        searchIndex: false,
      },
      customerLocale: { filterIndex: false, searchIndex: false },
      discountApplications: {
        filterIndex: false,
        searchIndex: false,
      },
      discountCodes: { filterIndex: false },
      dutiesIncluded: { filterIndex: false, searchIndex: false },
      edited: { filterIndex: false, searchIndex: false },
      email: true,
      estimatedTaxes: { filterIndex: false, searchIndex: false },
      financialStatus: { searchIndex: false },
      fulfillable: { filterIndex: false, searchIndex: false },
      fulfillmentStatus: { searchIndex: false },
      fulfillmentsCount: { filterIndex: false, searchIndex: false },
      fullyPaid: { filterIndex: false, searchIndex: false },
      hasTimelineComment: { filterIndex: false, searchIndex: false },
      landingSite: { filterIndex: false },
      legacyResourceId: { filterIndex: false, searchIndex: false },
      lineItems: true,
      location: { searchIndex: false },
      merchantEditable: { filterIndex: false, searchIndex: false },
      merchantEditableErrors: {
        filterIndex: false,
        searchIndex: false,
      },
      merchantOfRecordAppId: {
        filterIndex: false,
        searchIndex: false,
      },
      name: true,
      netPaymentSet: { filterIndex: false, searchIndex: false },
      note: true,
      noteAttributes: { filterIndex: false, searchIndex: false },
      orderStatusUrl: { filterIndex: false, searchIndex: false },
      originalTotalAdditionalFeesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      originalTotalDutiesSet: {
        filterIndex: false,
        searchIndex: false,
      },
      originalTotalPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      paymentGatewayNames: { filterIndex: false },
      phone: { filterIndex: false },
      poNumber: { filterIndex: false },
      presentmentCurrency: { filterIndex: false, searchIndex: false },
      processedAt: { searchIndex: false },
      processingMethod: { filterIndex: false, searchIndex: false },
      referringSite: { filterIndex: false },
      refundDiscrepencySet: {
        filterIndex: false,
        searchIndex: false,
      },
      refundable: { filterIndex: false, searchIndex: false },
      requiresShipping: { filterIndex: false, searchIndex: false },
      restockable: { filterIndex: false, searchIndex: false },
      retailLocation: { searchIndex: false },
      returnStatus: { filterIndex: false, searchIndex: false },
      risk: { filterIndex: false, searchIndex: false },
      shippingAddress: { filterIndex: false },
      shop: { searchIndex: false },
      shopifyCreatedAt: { filterIndex: false, searchIndex: false },
      shopifyProtect: { filterIndex: false, searchIndex: false },
      shopifyUpdatedAt: { filterIndex: false, searchIndex: false },
      sourceIdentifier: { filterIndex: false },
      sourceName: { filterIndex: false, searchIndex: false },
      sourceUrl: { filterIndex: false },
      subtotalPrice: { filterIndex: false, searchIndex: false },
      subtotalPriceSet: { filterIndex: false, searchIndex: false },
      tags: true,
      taxExempt: { filterIndex: false, searchIndex: false },
      taxLines: { filterIndex: false, searchIndex: false },
      taxesIncluded: { filterIndex: false, searchIndex: false },
      test: { filterIndex: false, searchIndex: false },
      token: { filterIndex: false, searchIndex: false },
      totalCapturableSet: { filterIndex: false, searchIndex: false },
      totalCashRoundingAdjustment: {
        filterIndex: false,
        searchIndex: false,
      },
      totalDiscounts: { filterIndex: false, searchIndex: false },
      totalDiscountsSet: { filterIndex: false, searchIndex: false },
      totalLineItemsPrice: { filterIndex: false, searchIndex: false },
      totalLineItemsPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      totalOutstanding: { filterIndex: false, searchIndex: false },
      totalOutstandingSet: { filterIndex: false, searchIndex: false },
      totalPrice: { filterIndex: false, searchIndex: false },
      totalPriceSet: { filterIndex: false, searchIndex: false },
      totalReceivedSet: { filterIndex: false, searchIndex: false },
      totalRefundedSet: { filterIndex: false, searchIndex: false },
      totalRefundedShippingSet: {
        filterIndex: false,
        searchIndex: false,
      },
      totalShippingPriceSet: {
        filterIndex: false,
        searchIndex: false,
      },
      totalTax: { filterIndex: false, searchIndex: false },
      totalTaxSet: { filterIndex: false, searchIndex: false },
      totalTipReceived: { filterIndex: false, searchIndex: false },
      totalTipReceivedSet: { filterIndex: false, searchIndex: false },
      totalWeight: { filterIndex: false, searchIndex: false },
      transactionsCount: { filterIndex: false, searchIndex: false },
      unpaid: { filterIndex: false, searchIndex: false },
    },
  },
};
